version: '3.8'
services:
  arkmanweb_app:
    container_name: arkmanweb_app
    restart: always
    env_file:
      - .env
    build: .
    develop:
      watch:
        - action: sync
          path: ./
          target: /
    networks:
      - db_network
      - web_network
    volumes:
      - ./templates:/templates
  arkmanweb_nginx:
    container_name: arkmanweb_nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - arkmanweb_app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge