services:
  - type: web
    name: flask-datta-pro
    plan: starter
    env: python
    region: oregon  # region should be same as your database region.
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:flask_app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
